name: "godot-ci export"
on:
  push:
    branch:
      - "master"

env:
  GODOT_VERSION: 3.3.3
  EXPORT_NAME: o.o

jobs:
  export-windows:
    name: Build Windows
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export "Windows" ./build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}-windows
          path: build/windows

  export-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --export "Linux" ./build/linux/$EXPORT_NAME.out
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}-linux
          path: build/linux

  export-mac:
    name: Build Mac
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac" ./build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}-mac
          path: build/mac

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [export-windows, export-linux, export-mac]
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: ${EXPORT_NAME}-windows
          path: .
      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: ${EXPORT_NAME}-linux
          path: .
      - name: Download Mac artifact
        uses: actions/download-artifact@v2
        with:
          name: ${EXPORT_NAME}-mac
          path: .
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d-%H%M%S')"
      - name: Debug
        run: |
          ls -la
          pwd
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            ${EXPORT_NAME}.zip
            ${EXPORT_NAME}.exe
            ${EXPORT_NAME}.out
